### ISSUE TITLE
UnhandledPromiseRejectionWarning: req.on is not a function

### ISSUE THREAD

**Issue by Extarys** [TheNoim/fastify-vue#7]
Using this, I get a lot of errors:
```
fastify
  .register(require('fastify-vue-plugin'), {
    config: require('../nuxt.config.js')
  })
  .after(e => {
    if (e) consola.trace(e)
    fastify.nuxt('/') // is equals: index.vue
    fastify.nuxt('/security')
    fastify.nuxt(
      '/security/:userUUID/:emailVerificationCode'
    )
    fastify.nuxt('/u')
    fastify.nuxt('/u/:id')
  })
```

Version: `"fastify-vue-plugin": "^1.2.3"`

Error:

```
(node:25731) UnhandledPromiseRejectionWarning: TypeError: req.on is not a function
    at Object.handler (/test/node_modules/webpack-hot-middleware/middleware.js:103:11)
    at middleware (/test/node_modules/webpack-hot-middleware/middleware.js:38:17)
    at P (/test/node_modules/nuxt/node_modules/pify/index.js:32:6)
    at new Promise (<anonymous>)
    at /test/node_modules/nuxt/node_modules/pify/index.js:6:9
    at Renderer.ret [as webpackHotMiddleware] (/test/node_modules/nuxt/node_modules/pify/index.js:55:86)
    at useMiddleware (/test/node_modules/nuxt/dist/nuxt.js:1957:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
(node:25731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by g0tt** [comment]
sent PR #12

**Comment by TheNoim** [comment]
Thanks. #13 and fastify-vue-plugin@1.3.0 are online now.
